import "server-only";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "@/db";
import { dailyApplications, dwData, itCodeAssignments, workerProfiles } from "@/db/schema";
import type { ReleaseReason } from "@/lib/dw-code-pool";

/** Same pattern as dw-code-pool.ts/workforce-request.ts — accepts `db` or an existing transaction so this composes into a larger atomic orchestration. */
type Executor = typeof db | Parameters<Parameters<typeof db.transaction>[0]>[0];

/**
 * MISSION E — IT CODE assignment/release history. Independent lifecycle
 * from DW Code (mission section 8/22): IT Code values come from the
 * external attendance system, never generated by this app — no
 * prefix/pool/sequence here, only assign/release/reuse history.
 *
 * `dw_data.it_code` stays the source-of-truth mirror every existing
 * screen reads (fingerprint-it-code-list.ts); `worker_profiles.fingerprint_code`
 * / `fingerprint_status` and `daily_applications.it_code` are the SAME
 * two secondary mirrors the existing PATCH /api/fingerprint/it-code
 * handler already writes — this module keeps writing all three in one
 * transaction, exactly like that handler, so nothing already depending
 * on those mirrors sees a behavior change.
 */

export type AssignItCodeInput = {
  itCode: string;
  workerId: string;
  employmentSessionId: string;
  dwDataId: string;
  dailyApplicationId: string;
  cccd: string;
  assignedBy: string;
};

export type AssignItCodeResult =
  | { ok: true; assignmentId: string }
  | { ok: false; error: "IT_CODE_ALREADY_ACTIVE" | "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" };

/** One active IT Code cannot belong to two workers simultaneously (mission section 8) — enforced here AND by a DB partial unique index. */
export async function assignItCode(input: AssignItCodeInput, executor: Executor = db): Promise<AssignItCodeResult> {
  const itCode = input.itCode.trim();
  if (executor === db) return db.transaction((tx) => assignItCode(input, tx));
  const tx = executor;
  {
    const [codeInUse] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.itCode, itCode), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (codeInUse) return { ok: false, error: "IT_CODE_ALREADY_ACTIVE" as const };

    const [workerHasActive] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.workerId, input.workerId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (workerHasActive) return { ok: false, error: "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" as const };

    const [created] = await tx
      .insert(itCodeAssignments)
      .values({
        itCode,
        workerId: input.workerId,
        employmentSessionId: input.employmentSessionId,
        dwDataId: input.dwDataId,
        assignedBy: input.assignedBy,
      })
      .returning({ id: itCodeAssignments.id });

    await tx
      .update(dwData)
      .set({ itCode, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: input.assignedBy })
      .where(eq(dwData.id, input.dwDataId));
    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: itCode, fingerprintStatus: "DA_CAP", updatedAt: new Date() })
      .where(and(eq(workerProfiles.cccd, input.cccd), isNull(workerProfiles.deletedAt)));
    await tx.update(dailyApplications).set({ itCode, updatedAt: new Date() }).where(eq(dailyApplications.id, input.dailyApplicationId));

    return { ok: true, assignmentId: created.id };
  }
}

export type ReleaseItCodeInput = {
  employmentSessionId: string;
  dailyApplicationId: string;
  /**
   * MISSION E pre-migration review — needed ONLY for the legacy-compatibility fallback below
   * (worker's CCCD to clear the worker_profiles mirror, dw_data.id to check/clear the it_code
   * mirror, when no it_code_assignments history row exists for this session at all).
   */
  workerId: string;
  dwDataId: string | null;
  releasedBy: string;
  releaseReason: ReleaseReason;
  note?: string | null;
};

export type ReleaseItCodeResult = { released: boolean; itCode: string | null };

async function clearItCodeMirrors(tx: Executor, dwDataId: string, workerId: string, dailyApplicationId: string, releasedBy: string): Promise<void> {
  await tx
    .update(dwData)
    .set({ itCode: null, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: releasedBy })
    .where(eq(dwData.id, dwDataId));

  const [worker] = await tx.select({ cccd: workerProfiles.cccd }).from(workerProfiles).where(eq(workerProfiles.id, workerId)).limit(1);
  if (worker) {
    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: null, fingerprintStatus: "CHUA_CAP", updatedAt: new Date() })
      .where(eq(workerProfiles.cccd, worker.cccd));
  }

  await tx.update(dailyApplications).set({ itCode: null, updatedAt: new Date() }).where(eq(dailyApplications.id, dailyApplicationId));
}

/**
 * Idempotent — releasing an employment session with no active IT Code assignment is a safe
 * no-op (mission section 46) — UNLESS the `dw_data.it_code` mirror is still populated for this
 * EXACT worker/dw_data row, in which case that's a code assigned through the legacy bulk
 * `PATCH /api/fingerprint/it-code` screen (deliberately left untouched by this mission — see PR
 * body — it never writes an `it_code_assignments` history row). Clearing the mirrors in THAT
 * case is safe and unambiguous (this employment session's OWN current dw_data row, never another
 * worker's) — it is NOT a historical backfill of assignment history, only the same 3-mirror
 * clear this function already performs for the tracked-history case, so a departed worker never
 * keeps showing an IT Code they no longer hold and a future assignment of the same external code
 * to someone else is never left showing stale, disagreeing values.
 */
export async function releaseItCode(input: ReleaseItCodeInput, executor: Executor = db): Promise<ReleaseItCodeResult> {
  if (executor === db) return db.transaction((tx) => releaseItCode(input, tx));
  const tx = executor;
  {
    const [active] = await tx
      .select({
        id: itCodeAssignments.id,
        itCode: itCodeAssignments.itCode,
        dwDataId: itCodeAssignments.dwDataId,
        workerId: itCodeAssignments.workerId,
      })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.employmentSessionId, input.employmentSessionId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);

    if (active) {
      await tx
        .update(itCodeAssignments)
        .set({ releasedAt: new Date(), releasedBy: input.releasedBy, releaseReason: input.releaseReason, note: input.note ?? null })
        .where(eq(itCodeAssignments.id, active.id));
      await clearItCodeMirrors(tx, active.dwDataId, active.workerId, input.dailyApplicationId, input.releasedBy);
      return { released: true, itCode: active.itCode };
    }

    // Legacy-compatibility fallback — see docblock above.
    if (!input.dwDataId) return { released: false, itCode: null };
    const [dw] = await tx.select({ itCode: dwData.itCode }).from(dwData).where(eq(dwData.id, input.dwDataId)).limit(1);
    if (!dw?.itCode) return { released: false, itCode: null };

    await clearItCodeMirrors(tx, input.dwDataId, input.workerId, input.dailyApplicationId, input.releasedBy);
    return { released: true, itCode: dw.itCode };
  }
}
