import "server-only";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "@/db";
import { dailyApplications, dwData, itCodeAssignments, workerProfiles } from "@/db/schema";
import type { ReleaseReason } from "@/lib/dw-code-pool";

/** Same pattern as dw-code-pool.ts/workforce-request.ts — accepts `db` or an existing transaction so this composes into a larger atomic orchestration. */
type Executor = typeof db | Parameters<Parameters<typeof db.transaction>[0]>[0];

/**
 * MISSION E — IT CODE assignment/release history. Independent lifecycle
 * from DW Code (mission section 8/22): IT Code values come from the
 * external attendance system, never generated by this app — no
 * prefix/pool/sequence here, only assign/release/reuse history.
 *
 * `dw_data.it_code` stays the source-of-truth mirror every existing
 * screen reads (fingerprint-it-code-list.ts); `worker_profiles.fingerprint_code`
 * / `fingerprint_status` and `daily_applications.it_code` are the SAME
 * two secondary mirrors the existing PATCH /api/fingerprint/it-code
 * handler already writes — this module keeps writing all three in one
 * transaction, exactly like that handler, so nothing already depending
 * on those mirrors sees a behavior change.
 */

export type AssignItCodeInput = {
  itCode: string;
  workerId: string;
  employmentSessionId: string;
  dwDataId: string;
  dailyApplicationId: string;
  cccd: string;
  assignedBy: string;
};

export type AssignItCodeResult =
  | { ok: true; assignmentId: string }
  | { ok: false; error: "IT_CODE_ALREADY_ACTIVE" | "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" };

/** One active IT Code cannot belong to two workers simultaneously (mission section 8) — enforced here AND by a DB partial unique index. */
export async function assignItCode(input: AssignItCodeInput, executor: Executor = db): Promise<AssignItCodeResult> {
  const itCode = input.itCode.trim();
  if (executor === db) return db.transaction((tx) => assignItCode(input, tx));
  const tx = executor;
  {
    const [codeInUse] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.itCode, itCode), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (codeInUse) return { ok: false, error: "IT_CODE_ALREADY_ACTIVE" as const };

    const [workerHasActive] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.workerId, input.workerId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (workerHasActive) return { ok: false, error: "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" as const };

    const [created] = await tx
      .insert(itCodeAssignments)
      .values({
        itCode,
        workerId: input.workerId,
        employmentSessionId: input.employmentSessionId,
        dwDataId: input.dwDataId,
        assignedBy: input.assignedBy,
      })
      .returning({ id: itCodeAssignments.id });

    await tx
      .update(dwData)
      .set({ itCode, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: input.assignedBy })
      .where(eq(dwData.id, input.dwDataId));
    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: itCode, fingerprintStatus: "DA_CAP", updatedAt: new Date() })
      .where(and(eq(workerProfiles.cccd, input.cccd), isNull(workerProfiles.deletedAt)));
    await tx.update(dailyApplications).set({ itCode, updatedAt: new Date() }).where(eq(dailyApplications.id, input.dailyApplicationId));

    return { ok: true, assignmentId: created.id };
  }
}

export type ReleaseItCodeInput = {
  employmentSessionId: string;
  dailyApplicationId: string;
  releasedBy: string;
  releaseReason: ReleaseReason;
  note?: string | null;
};

export type ReleaseItCodeResult = { released: boolean; itCode: string | null };

/** Idempotent — releasing an employment session with no active IT Code assignment is a safe no-op (mission section 46). */
export async function releaseItCode(input: ReleaseItCodeInput, executor: Executor = db): Promise<ReleaseItCodeResult> {
  if (executor === db) return db.transaction((tx) => releaseItCode(input, tx));
  const tx = executor;
  {
    const [active] = await tx
      .select({
        id: itCodeAssignments.id,
        itCode: itCodeAssignments.itCode,
        dwDataId: itCodeAssignments.dwDataId,
        workerId: itCodeAssignments.workerId,
      })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.employmentSessionId, input.employmentSessionId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (!active) return { released: false, itCode: null };

    await tx
      .update(itCodeAssignments)
      .set({ releasedAt: new Date(), releasedBy: input.releasedBy, releaseReason: input.releaseReason, note: input.note ?? null })
      .where(eq(itCodeAssignments.id, active.id));

    await tx
      .update(dwData)
      .set({ itCode: null, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: input.releasedBy })
      .where(eq(dwData.id, active.dwDataId));

    const [worker] = await tx.select({ cccd: workerProfiles.cccd }).from(workerProfiles).where(eq(workerProfiles.id, active.workerId)).limit(1);
    if (worker) {
      await tx
        .update(workerProfiles)
        .set({ fingerprintCode: null, fingerprintStatus: "CHUA_CAP", updatedAt: new Date() })
        .where(eq(workerProfiles.cccd, worker.cccd));
    }

    await tx.update(dailyApplications).set({ itCode: null, updatedAt: new Date() }).where(eq(dailyApplications.id, input.dailyApplicationId));

    return { released: true, itCode: active.itCode };
  }
}
