import "server-only";
import { and, eq, isNull } from "drizzle-orm";
import { db } from "@/db";
import { dailyApplications, dwData, employmentSessions, itCodeAssignments, workerProfiles } from "@/db/schema";
import type { ReleaseReason } from "@/lib/dw-code-pool";

/** Same pattern as dw-code-pool.ts/workforce-request.ts — accepts `db` or an existing transaction so this composes into a larger atomic orchestration. */
type Executor = typeof db | Parameters<Parameters<typeof db.transaction>[0]>[0];

/**
 * MISSION E — IT CODE assignment/release history. Independent lifecycle
 * from DW Code (mission section 8/22): IT Code values come from the
 * external attendance system, never generated by this app — no
 * prefix/pool/sequence here, only assign/release/reuse history.
 *
 * `dw_data.it_code` stays the source-of-truth mirror every existing
 * screen reads (fingerprint-it-code-list.ts); `worker_profiles.fingerprint_code`
 * / `fingerprint_status` and `daily_applications.it_code` are the SAME
 * two secondary mirrors the existing PATCH /api/fingerprint/it-code
 * handler already writes — this module keeps writing all three in one
 * transaction, exactly like that handler, so nothing already depending
 * on those mirrors sees a behavior change.
 *
 * MIRROR CONTRACT (mission F2 section 12-13/251) — all THREE mirrors
 * (`dw_data.it_code`, `worker_profiles.fingerprint_code`, `daily_applications.
 * it_code`) are CURRENT-MIRRORS, never historical/append-only: each reflects
 * only "what IT Code does this worker/engagement hold RIGHT NOW", overwritten
 * on assign and cleared to NULL on release — never left showing a stale value
 * for a worker who no longer holds that code. `daily_applications.it_code`'s
 * "current" is naturally scoped to that one engagement's lifetime (a new
 * registration cycle gets its own `daily_applications` row), unlike
 * `dw_data`/`worker_profiles` which are per-worker and get overwritten across
 * engagements. `it_code_assignments` (this module's own table) is the ONLY
 * historical source — one row per assignment PERIOD, `releasedAt` marking
 * active vs. history — any reader needing "who has EVER held code X" or "what
 * codes has this worker held over time" must query it directly, never infer
 * history from a mirror's current value.
 */

export type AssignItCodeInput = {
  itCode: string;
  workerId: string;
  employmentSessionId: string;
  dwDataId: string;
  dailyApplicationId: string;
  cccd: string;
  assignedBy: string;
};

export type AssignItCodeResult =
  | { ok: true; assignmentId: string }
  | { ok: false; error: "IT_CODE_ALREADY_ACTIVE" | "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" };

/** One active IT Code cannot belong to two workers simultaneously (mission section 8) — enforced here AND by a DB partial unique index. */
export async function assignItCode(input: AssignItCodeInput, executor: Executor = db): Promise<AssignItCodeResult> {
  const itCode = input.itCode.trim();
  if (executor === db) return db.transaction((tx) => assignItCode(input, tx));
  const tx = executor;
  {
    const [codeInUse] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.itCode, itCode), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (codeInUse) return { ok: false, error: "IT_CODE_ALREADY_ACTIVE" as const };

    const [workerHasActive] = await tx
      .select({ id: itCodeAssignments.id })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.workerId, input.workerId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);
    if (workerHasActive) return { ok: false, error: "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" as const };

    const [created] = await tx
      .insert(itCodeAssignments)
      .values({
        itCode,
        workerId: input.workerId,
        employmentSessionId: input.employmentSessionId,
        dwDataId: input.dwDataId,
        assignedBy: input.assignedBy,
      })
      .returning({ id: itCodeAssignments.id });

    await tx
      .update(dwData)
      .set({ itCode, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: input.assignedBy })
      .where(eq(dwData.id, input.dwDataId));
    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: itCode, fingerprintStatus: "DA_CAP", updatedAt: new Date() })
      .where(and(eq(workerProfiles.cccd, input.cccd), isNull(workerProfiles.deletedAt)));
    await tx.update(dailyApplications).set({ itCode, updatedAt: new Date() }).where(eq(dailyApplications.id, input.dailyApplicationId));

    return { ok: true, assignmentId: created.id };
  }
}

export type ReleaseItCodeInput = {
  employmentSessionId: string;
  dailyApplicationId: string;
  /**
   * MISSION E pre-migration review — needed ONLY for the legacy-compatibility fallback below
   * (worker's CCCD to clear the worker_profiles mirror, dw_data.id to check/clear the it_code
   * mirror, when no it_code_assignments history row exists for this session at all).
   */
  workerId: string;
  dwDataId: string | null;
  releasedBy: string;
  releaseReason: ReleaseReason;
  note?: string | null;
};

export type ReleaseItCodeResult = { released: boolean; itCode: string | null };

async function clearItCodeMirrors(tx: Executor, dwDataId: string, workerId: string, dailyApplicationId: string, releasedBy: string): Promise<void> {
  await tx
    .update(dwData)
    .set({ itCode: null, itCodeUpdatedAt: new Date(), itCodeUpdatedBy: releasedBy })
    .where(eq(dwData.id, dwDataId));

  const [worker] = await tx.select({ cccd: workerProfiles.cccd }).from(workerProfiles).where(eq(workerProfiles.id, workerId)).limit(1);
  if (worker) {
    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: null, fingerprintStatus: "CHUA_CAP", updatedAt: new Date() })
      .where(eq(workerProfiles.cccd, worker.cccd));
  }

  await tx.update(dailyApplications).set({ itCode: null, updatedAt: new Date() }).where(eq(dailyApplications.id, dailyApplicationId));
}

/**
 * Idempotent — releasing an employment session with no active IT Code assignment is a safe
 * no-op (mission section 46) — UNLESS the `dw_data.it_code` mirror is still populated for this
 * EXACT worker/dw_data row, in which case that's a code assigned through the legacy bulk
 * `PATCH /api/fingerprint/it-code` screen (deliberately left untouched by this mission — see PR
 * body — it never writes an `it_code_assignments` history row). Clearing the mirrors in THAT
 * case is safe and unambiguous (this employment session's OWN current dw_data row, never another
 * worker's) — it is NOT a historical backfill of assignment history, only the same 3-mirror
 * clear this function already performs for the tracked-history case, so a departed worker never
 * keeps showing an IT Code they no longer hold and a future assignment of the same external code
 * to someone else is never left showing stale, disagreeing values.
 */
export async function releaseItCode(input: ReleaseItCodeInput, executor: Executor = db): Promise<ReleaseItCodeResult> {
  if (executor === db) return db.transaction((tx) => releaseItCode(input, tx));
  const tx = executor;
  {
    const [active] = await tx
      .select({
        id: itCodeAssignments.id,
        itCode: itCodeAssignments.itCode,
        dwDataId: itCodeAssignments.dwDataId,
        workerId: itCodeAssignments.workerId,
      })
      .from(itCodeAssignments)
      .where(and(eq(itCodeAssignments.employmentSessionId, input.employmentSessionId), isNull(itCodeAssignments.releasedAt)))
      .limit(1);

    if (active) {
      await tx
        .update(itCodeAssignments)
        .set({ releasedAt: new Date(), releasedBy: input.releasedBy, releaseReason: input.releaseReason, note: input.note ?? null })
        .where(eq(itCodeAssignments.id, active.id));
      await clearItCodeMirrors(tx, active.dwDataId, active.workerId, input.dailyApplicationId, input.releasedBy);
      return { released: true, itCode: active.itCode };
    }

    // Legacy-compatibility fallback — see docblock above.
    if (!input.dwDataId) return { released: false, itCode: null };
    const [dw] = await tx.select({ itCode: dwData.itCode }).from(dwData).where(eq(dwData.id, input.dwDataId)).limit(1);
    if (!dw?.itCode) return { released: false, itCode: null };

    await clearItCodeMirrors(tx, input.dwDataId, input.workerId, input.dailyApplicationId, input.releasedBy);
    return { released: true, itCode: dw.itCode };
  }
}

export type UpdateWorkerBiometricInput = {
  workerId: string;
  fingerprintCode: string | null;
  fingerprintDevice: string | null;
  fingerprintStatus: string | null;
  updatedBy: string;
};

export type UpdateWorkerBiometricResult =
  | { ok: true; itCodeRoute: "CANONICAL" | "DIRECT_NO_ACTIVE_ENGAGEMENT" }
  | { ok: false; error: "WORKER_NOT_FOUND" | "IT_CODE_ALREADY_ACTIVE" | "WORKER_ALREADY_HAS_ACTIVE_IT_CODE" };

/**
 * MISSION F2 section 11/250 — the ADMIN "Biometric" edit routes (PATCH /api/worker-profiles/by-id/
 * [workerId]/fingerprint and its legacy CCCD-keyed twin PATCH /api/worker-profiles/[cccd]) used to
 * write `worker_profiles.fingerprint_code` directly — bypassing `it_code_assignments` history
 * entirely AND never touching the other two mirrors (`dw_data.it_code`, `daily_applications.
 * it_code`), which is exactly the MISSING_MIRROR/CONFLICTING_VALUES state the diagnostic script
 * flags. It also silently let one admin edit overwrite an IT Code another worker's assignment was
 * still actively holding — assignItCode()'s IT_CODE_ALREADY_ACTIVE/WORKER_ALREADY_HAS_ACTIVE_IT_CODE
 * checks now catch that instead.
 *
 * When the worker has an ACTIVE employment session with a linked dw_data row (the same
 * session/mirror context assignItCode()/releaseItCode() need), the IT Code identity change is
 * routed through the canonical service — same assign/release/no-op decision as the bulk PATCH
 * /api/fingerprint/it-code handler. Device/status metadata (not part of the IT Code identity) is
 * still written directly afterward, preserving this admin tool's existing free-form status/device
 * override UX.
 *
 * When there is no active session or no matching dw_data row, there is no employment context to
 * attach an assignment-history row to — this falls back to a direct mirror write (matches the
 * original behavior for that edge case; documented, not silently dropped).
 */
export async function updateWorkerBiometric(input: UpdateWorkerBiometricInput, executor: Executor = db): Promise<UpdateWorkerBiometricResult> {
  if (executor === db) return db.transaction((tx) => updateWorkerBiometric(input, tx));
  const tx = executor;
  {
    const [worker] = await tx
      .select({ id: workerProfiles.id, cccd: workerProfiles.cccd })
      .from(workerProfiles)
      .where(and(eq(workerProfiles.id, input.workerId), isNull(workerProfiles.deletedAt)))
      .limit(1);
    if (!worker) return { ok: false, error: "WORKER_NOT_FOUND" as const };

    const [session] = await tx
      .select({ id: employmentSessions.id, dailyApplicationId: employmentSessions.dailyApplicationId })
      .from(employmentSessions)
      .where(and(eq(employmentSessions.workerId, worker.id), eq(employmentSessions.status, "APPROVED"), isNull(employmentSessions.endDate)))
      .limit(1);
    const [dw] = await tx
      .select({ id: dwData.id })
      .from(dwData)
      .where(and(eq(dwData.cccd, worker.cccd), isNull(dwData.deletedAt)))
      .limit(1);

    const itCode = input.fingerprintCode?.trim() || null;

    if (session?.dailyApplicationId && dw) {
      const actionInput = {
        employmentSessionId: session.id,
        dailyApplicationId: session.dailyApplicationId,
        workerId: worker.id,
        dwDataId: dw.id,
        releasedBy: input.updatedBy,
        releaseReason: "MANUAL_CORRECTION" as const,
      };
      const [currentActive] = await tx
        .select({ itCode: itCodeAssignments.itCode })
        .from(itCodeAssignments)
        .where(and(eq(itCodeAssignments.employmentSessionId, session.id), isNull(itCodeAssignments.releasedAt)))
        .limit(1);

      if (itCode === null) {
        if (currentActive) await releaseItCode(actionInput, tx);
      } else if (currentActive?.itCode !== itCode) {
        if (currentActive) await releaseItCode(actionInput, tx);
        const assignResult = await assignItCode(
          { itCode, workerId: worker.id, employmentSessionId: session.id, dwDataId: dw.id, dailyApplicationId: session.dailyApplicationId, cccd: worker.cccd, assignedBy: input.updatedBy },
          tx,
        );
        if (!assignResult.ok) return { ok: false, error: assignResult.error };
      }

      // Device/status metadata is not part of the IT Code identity assignItCode()/releaseItCode()
      // manage — write it directly, after the canonical call so it is never clobbered by the
      // fixed DA_CAP/CHUA_CAP status those functions set on the code-identity mirror fields.
      await tx
        .update(workerProfiles)
        .set({ fingerprintDevice: input.fingerprintDevice, fingerprintStatus: input.fingerprintStatus || "DA_CAP", fingerprintCreatedAt: new Date(), updatedAt: new Date() })
        .where(eq(workerProfiles.id, worker.id));
      return { ok: true, itCodeRoute: "CANONICAL" as const };
    }

    await tx
      .update(workerProfiles)
      .set({ fingerprintCode: itCode, fingerprintDevice: input.fingerprintDevice, fingerprintStatus: input.fingerprintStatus || "DA_CAP", fingerprintCreatedAt: new Date(), updatedAt: new Date() })
      .where(eq(workerProfiles.id, worker.id));
    return { ok: true, itCodeRoute: "DIRECT_NO_ACTIVE_ENGAGEMENT" as const };
  }
}
